fastlane_version '2.200.0'

skip_docs

##############
### UPDATE ###
##############

desc 'Update metadata from the libPhoneNumber'
lane :update_metadata do 
    # Make sure we run this lane on the master branch.
    ensure_git_branch branch: 'master'

    # Update the code.
    update_phone_metadata
end
