fastlane_version '2.200.0'

skip_docs

##############
### UPDATE ###
##############

desc 'Update metadata from the libPhoneNumber'
lane :update_metadata do 
    # Make sure we run this lane on the master branch.
    ensure_git_branch branch: 'master'

    # Update the code.
    update_phone_metadata

    # Commit the code
    git_commit path:    'PhoneNumberKit/Resources/*',
               message: 'Update the metadata to the latest version'

    # Push the code to Github.
    push_to_git_remote
end
